### ISSUE TITLE
ゴールする判断や表示がある

### ISSUE THREAD

**Issue by c2cb** [RenNakasato/ProjExD#11]
https://github.com/RenNakasato/ProjExD/blob/a586e18bfc0c1f6d1950a6f4ca28d6ded566832a/ex03/maze.py#L31

自分もゴールした際の判断を入れようとしていましたが、関数を作って判断する方法は思いつかず、いったん保留にしました。とても参考になりました。ありがとうございました。

**Comment by RenNakasato** [comment]
ありがとうございます。
