### ISSUE TITLE
加速する追加機能

### ISSUE THREAD

**Issue by c2cb** [RenNakasato/ProjExD#12]
https://github.com/RenNakasato/ProjExD/blob/5dba226df38658f3ccd05e2795107f283ea8391b/ex04_kari/dodge_bomb.py#L51

READMEを読んで、加速する機能があると驚きました。
しかしどこで追加されているのかがぱっと見つからないので、コメントを付けて頂けると個人的にありがたいです。
とても面白そうなので、ぜひ完成させてください。

**Comment by RenNakasato** [comment]
コメントをつける癖をつけるようにします。
ご指摘ありがとうございます。
