### ISSUE TITLE
コメント

### ISSUE THREAD

**Issue by sugaikota** [RenNakasato/ProjExD#4]
https://github.com/RenNakasato/ProjExD/blob/a272dffc101126e3c80b384271774cb677d346a6/ex02/calc.py#L75
似たようなコードが並んでいるので、for文などで回して表示すると、見やすいかもしれません。

**Comment by RenNakasato** [comment]
ご指摘ありがとうございます。
直しました。
この件は＃５と同様な内容のため、コードに関してはそちらをご確認ください
