### ISSUE TITLE
2乗、3乗、ルート、すごい

### ISSUE THREAD

**Issue by c2cb** [RenNakasato/ProjExD#6]
https://github.com/RenNakasato/ProjExD/blob/a272dffc101126e3c80b384271774cb677d346a6/ex02/calc.py#L33

四則演算だけでなく、中高大社会人がよく利用する演算を入れられる技術があってすごいと思いました。
完璧です、一切の隙もありません。１人で100人分の仕事をこの短時間でできることがすごいと思いました。
もうここまで来てしまっては、何もかも退屈に見えてくるかもしれませんね。
他のアプリとの差別化を図って、全世界が飛び驚くほどの追加機能を作りましょう。
あなたなら、できます。ぜひ、このままグングンと知識を吸収して、地球を美しくしてください。

**Comment by RenNakasato** [comment]
ありがとうございます。
精進していきます。
