### ISSUE TITLE
コメントアウトが欲しい

### ISSUE THREAD

**Issue by Yawn-MP** [RenNakasato/ProjExD#8]
https://github.com/RenNakasato/ProjExD/blob/a586e18bfc0c1f6d1950a6f4ca28d6ded566832a/ex03/maze.py#L31
コメントアウトしてくれると見やすくなるかも。
BTW、時間計っているの良きですね

**Comment by RenNakasato** [comment]
コメントアウトするのを忘れていました。
ご指摘ありがとうございます。
